### PR TITLE
Doubleandsingle

### PR DESCRIPTION
**Pull request by ingalls**
- Some ESRI servers need encoded geometries
- Some don't care
- Some reject it....

Next pass will be to setup a mock server for testing as I did with the ImageServer portion of the code

### CODE REVIEW

**Comment by iandees** [comment]
What servers expect the geometry to be double-encoded?

**Comment by ajturner** [comment]
Yep - curious

**Comment by ingalls** [comment]
See: https://github.com/openaddresses/esri-dump/pull/23#issue-88915928

**Comment by ingalls** [comment]
Any thoughts here?

**Comment by iandees** [comment]
I don't think this requires a double-encoding. For example, this request works fine:

```
http://72.205.198.131/ArcGIS/rest/services/Allen/Allen/MapServer/32/query?geometry=2170794.91841735%2C1714455.05787088%2C2299020.26137561%2C1829440.6366263&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&returnCountOnly=true&returnGeometry=false&outSR=4326&outFields=*&f=json
```

That's a normal, single-encoded URL with the following parameters:

```
geometry:2170794.91841735,1714455.05787088,2299020.26137561,1829440.6366263
geometryType:esriGeometryEnvelope
spatialRel:esriSpatialRelIntersects
returnCountOnly:true
returnGeometry:false
outSR:4326
outFields:*
f:json
```

**Pull request closed without merging**
