### PR TITLE
Accept FeatureServers; improved test coverage & error handling

### PR DESCRIPTION
**Pull request by aaronpdennis**
- handles `FeatureServer` endpoints like [this one](https://services1.arcgis.com/d6RVn1EQDwncFtWo/arcgis/rest/services/Campbell_VA_Addresses/FeatureServer/0)
- verifies valid GeoJSON output from some ESRI sample `FeatureSever` and `MapServer` endpoints
- if no field is of type `esriFieldTypeOID`, looks for another likely Object ID field or throws an exception
- more descriptive error messages
- minor version bump

### CODE REVIEW

**Comment by aaronpdennis** [comment]
#28 fixed
screen shot 2016-05-18 at 2 42 06 pm

**Comment by iandees** [comment]
Great, thanks for doing this!

Just so you know, we don't really use this repo in practice anymore. All the ESRI scraping stuff we do happens in the Python [machine](https://github.com/openaddresses/machine) code.

**Comment by aaronpdennis** [comment]
@iandees I've seen the machine code, I'm sure it's a little more robust than this repo. Just like the idea of a simple way to dump ESRI endpoints to GeoJSON!

**Comment by iandees** [comment]
❤️  me too! Thanks for your contribution.

**Pull request merged**
